# Generated by Django 4.1.7 on 2023-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="frontInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="")),
                ("title", models.CharField(max_length=20)),
                ("shortDesc", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=777)),
            ],
        ),
    ]
