# Generated by Django 4.1.7 on 2023-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="static/AJF")),
                ("title", models.CharField(max_length=30)),
                ("Desc", models.CharField(max_length=10000)),
                ("link", models.URLField(max_length=777)),
            ],
        ),
        migrations.AlterField(
            model_name="frontinfo",
            name="thumbnail",
            field=models.ImageField(upload_to="static/AJF"),
        ),
    ]
