# Generated by Django 4.1.7 on 2023-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_detail_alter_frontinfo_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail", name="Desc", field=models.TextField(max_length=10000),
        ),
    ]
